name: Build Scylla and run tests

on:
  push:
    branches-ignore: [ '_**' ]
  pull_request:

# Cancel previous versions of this job that are still running.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: self-hosted
    steps:
      - name: Clone scylla
        uses: actions/checkout@v4
        with:
          path: scylla

      - name: Clone symcrypt
        uses: actions/checkout@v4
        with:
          repository: msprotz/SymCrypt
          path: symcrypt
          submodules: true
          ref: protz/scylla

      - name: Build symcrypt
        working-directory: symcrypt
        run: |
          nix develop "$GITHUB_WORKSPACE/scylla" --command scripts/build.py cmake build --no-fips --no-asm --config Release

      - name: Build and test scylla
        working-directory: scylla
        run: |
          export SYMCRYPT_HOME=$GITHUB_WORKSPACE/symcrypt
          nix develop --command make test

      - name: Check output
        working-directory: scylla
        run: |
          # Check that there are no differences between the generated outputs
          # and the committed outputs.
          if git diff --exit-code --quiet out > /dev/null; then
            echo "Ok: the regenerated files are the same as the checked out files"
          else
            echo "Error: the regenerated files differ from the checked out files"
            git diff out
            exit 1
          fi
